// Opt-in integration: real BiRefNet + LaMa, production CSP, native dialogs and exports.
const { app, BrowserWindow, dialog } = require('electron')
const fs = require('node:fs/promises'), path = require('node:path'), os = require('node:os')
const assert = require('node:assert/strict'), JSZip = require('jszip')
const catalog = require('../shared/ai-models.json')
const scratch = require('node:fs').mkdtempSync(path.join(os.tmpdir(), 'imejii-studio-test-'))
const report = process.env.IMEJII_AI_REPORT_DIR
const fixture = path.resolve(process.env.IMEJII_CUTOUT_FIXTURE || path.join(__dirname, 'fixture.svg'))
app.setPath('userData', path.join(scratch, 'profile')); app.setPath('sessionData', path.join(scratch, 'profile'))
BrowserWindow.prototype.show = function () {}
process.argv.push(fixture)
const errors = [], results = [], saved = [], pause = ms => new Promise(resolve => setTimeout(resolve, ms))
dialog.showMessageBoxSync = () => 1; dialog.showMessageBox = async () => ({ response: 1 })
dialog.showErrorBox = (title, message) => errors.push(title + ': ' + message)
dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [path.join(__dirname, 'fixture.svg')] })
dialog.showSaveDialog = async (...args) => { const options = args.at(-1), filePath = path.join(scratch, path.basename(options.defaultPath)); saved.push(filePath); return { canceled: false, filePath } }
app.on('web-contents-created', (_event, wc) => wc.on('console-message', event => { if (event.level === 'error') errors.push(event.message) }))
const deadline = setTimeout(() => { console.error('Studio timeout', errors); app.exit(2) }, 420000)
require(process.env.IMEJII_PACKAGED_MAIN || '../electron/main.cjs')
async function until(test, timeout = 15000) { const start = Date.now(); while (Date.now() - start < timeout) { if (await test()) return; await pause(100) } throw new Error('Studio state timeout: ' + errors.join('\n')) }
app.whenReady().then(async () => {
  const cache = path.join(scratch, 'profile/ai-models'); await fs.mkdir(cache, { recursive: true }); if (report) await fs.mkdir(report, { recursive: true })
  for (const id of ['birefnet-lite-v1', 'lama-v1']) { const name = catalog[id].sha256 + '.onnx'; await fs.copyFile(path.resolve(__dirname, '../build/ai-models', name), path.join(cache, name)) }
  await until(() => BrowserWindow.getAllWindows().length)
  const window = BrowserWindow.getAllWindows()[0], wc = window.webContents
  window.setMinimumSize(500, 600); window.setSize(1440, 1000); wc.setBackgroundThrottling(false)
  const js = script => wc.executeJavaScript(script)
  await until(async () => { try { return await js("Boolean(document.querySelector('#app')?.__vue_app__)") } catch { return false } })
  await js(`globalThis.stores = () => Reflect.ownKeys(document.querySelector('#app').__vue_app__._context.provides).map(k => document.querySelector('#app').__vue_app__._context.provides[k]).find(v=>v?._s); globalThis.library=stores()._s.get('library'); globalThis.ui=stores()._s.get('ui'); void 0`)
  await until(() => js('!!library.previewCanvas && !library.isRendering'))
  const original = await js('JSON.stringify({name:library.activeItem.name, edits:library.activeItem.edits, width:library.activeItem.width,height:library.activeItem.height})')
  const click = async (label, selector = 'body') => { await js(`(() => {const b=[...document.querySelector(${JSON.stringify(selector)}).querySelectorAll('button')].find(b=>b.textContent.trim()===${JSON.stringify(label)}); if(!b || b.disabled) throw new Error('Unavailable: '+${JSON.stringify(label)}); b.click()})()`); await pause(150) }
  const select = async (label, value) => { await js(`(() => {const l=[...document.querySelectorAll('.studio-controls label')].find(l=>l.textContent.trim().startsWith(${JSON.stringify(label)})); const s=l?.querySelector('select'); if(!s) throw new Error('No select: '+${JSON.stringify(label)}); s.value=${JSON.stringify(String(value))}; s.dispatchEvent(new Event('change',{bubbles:true}))})()`); await pause(150) }
  const slider = async (label, value) => { await js(`(() => {const s=[...document.querySelectorAll('.studio-controls input[type=number]')].find(s=>s.getAttribute('aria-label')?.startsWith(${JSON.stringify(label)})); if(!s) throw new Error('No slider: '+${JSON.stringify(label)}); s.value=${value}; s.dispatchEvent(new Event('input',{bubbles:true}))})()`); await pause(150) }
  const ready = () => until(() => js("[...document.querySelectorAll('.cutout button')].some(b=>b.textContent.trim()==='Apply as new photo' && !b.disabled) || !!document.querySelector('.cutout .error')"), 150000).then(async () => assert.equal(await js("document.querySelector('.cutout .error')?.textContent"), undefined))
  const pixels = () => js("document.querySelector('.cutout-canvas').toDataURL()").then(value => require('node:crypto').hash('sha256', value))
  const shot = async (name, width = 1440, height = 1000) => { if (!report) return; window.setSize(width + 1, height); await pause(150); window.setSize(width, height); await pause(250); await fs.writeFile(path.join(report, name), (await wc.capturePage()).toPNG()) }
  async function check(name, fn) { try { const detail = await fn(); results.push({ name, status: 'PASS', ...(detail ? { detail } : {}) }); console.log('PASS', name) } catch (e) { results.push({ name, status: 'FAIL', detail: e.message }); console.error('FAIL', name, e.message); throw e } }
  try {
    await js("ui.setMode('images'); void 0"); await click('Plugins')
    await click('Enable plugin', '.plugin-card:nth-of-type(1)'); await click('Enable plugin', '.plugin-card:nth-of-type(2)')
    await until(() => js("[...document.querySelectorAll('.local-model-panel')].every(p=>p.textContent.includes('Model verified'))"))
    wc.session.enableNetworkEmulation({ offline: true })
    await check('Real BiRefNet opens Subject Studio offline with all five workspaces', async () => {
      await click('Cut out the subject'); await ready()
      assert.equal(await js("document.querySelectorAll('.studio-navigation button').length"), 5)
      assert.equal(await js("document.querySelector('#cutout-title').textContent"), 'Subject Studio')
    })
    await check('Selective presets and rapid slider changes render, undo and redo without new inference', async () => {
      await click('Develop', '.studio-navigation'); await click('Color splash', '.studio-controls'); await ready()
      const splash = await pixels(); await slider('Subject exposure', -1); await slider('Subject exposure', -.5); await ready()
      const adjusted = await pixels(); assert.notEqual(adjusted, splash)
      await click('Undo style', '.cutout'); await ready(); assert.equal(await pixels(), splash)
      await click('Redo style', '.cutout'); await ready(); assert.equal(await pixels(), adjusted)
      await shot('studio-develop.png')
      await click('Portrait blur', '.studio-controls'); await ready(); assert.notEqual(await pixels(), adjusted)
      await shot('studio-portrait.png')
    })
    await check('Local background picker, fit and gradient use native authorized files', async () => {
      await click('Scene', '.studio-navigation'); await select('Background type', 'image')
      await until(() => js("document.querySelector('.composition-status')?.textContent.includes('Choose a background')"))
      await click('Choose background image', '.studio-controls'); await ready()
      assert.equal(await js("document.querySelector('.studio-filename').textContent"), 'fixture.svg')
      await select('Image fit', 'contain'); await ready(); await shot('studio-background.png')
      await select('Background type', 'gradient'); await ready(); await shot('studio-gradient.png')
    })
    await check('Product, sticker, opacity and subject crop produce matching preview geometry', async () => {
      await click('Frame', '.studio-navigation'); await click('Sticker', '.studio-controls'); await select('Output longest edge', 1024); await ready()
      assert.equal(await js("document.querySelector('.cutout-canvas').width"), 1024)
      await slider('Subject opacity', 60); await ready(); await shot('studio-sticker.png')
      await click('Product photo', '.studio-controls'); await select('Output longest edge', 1024); await ready()
      const product = await pixels(); await shot('studio-product.png')
      await js("document.documentElement.dataset.theme='light'; void 0"); await shot('studio-light.png', 1024, 740)
      await js("document.documentElement.dataset.theme='dark'; void 0"); await shot('studio-narrow.png', 620, 780); window.setSize(1440, 1000)
      await select('Framing', 'crop'); await select('Aspect ratio', '4:5'); await ready(); assert.notEqual(await pixels(), product)
      await shot('studio-crop.png')
    })
    await check('Mask PNG and SDXL ZIP export matching full source dimensions and polarity, without composition', async () => {
      await click('Send', '.studio-navigation'); await click('Export mask PNG', '.studio-controls')
      await until(async () => saved.length === 1 && await fs.stat(saved[0]).then(s=>s.size > 100,()=>false))
      await ready(); const maskBytes = await fs.readFile(saved[0]), source = JSON.parse(original)
      assert.equal(maskBytes.readUInt32BE(16), source.width); assert.equal(maskBytes.readUInt32BE(20), source.height)
      await click('Export image + mask for SDXL', '.studio-controls')
      await until(async () => saved.length === 2 && await fs.stat(saved[1]).then(s=>s.size > 100,()=>false)); await ready()
      const zip = await JSZip.loadAsync(await fs.readFile(saved[1])), manifest = JSON.parse(await zip.file('selection.json').async('string'))
      assert.deepEqual(Object.keys(zip.files).sort(), ['README.txt','image.png','mask.png','selection.json'])
      assert.equal(manifest.polarity, 'white-repaint-black-preserve'); assert.equal(manifest.width, source.width)
      const bundledMask = await zip.file('mask.png').async('nodebuffer'); assert.deepEqual(bundledMask, maskBytes)
      const image = await zip.file('image.png').async('nodebuffer'); assert.equal(image.readUInt32BE(16), source.width); assert.equal(image.readUInt32BE(20), source.height)
      await shot('studio-send.png')
    })
    await check('Product variant saves full geometry and style provenance while retaining the original', async () => {
      await click('Frame', '.studio-navigation'); await click('Product photo', '.studio-controls'); await select('Output longest edge', 1024); await ready()
      await click('Apply as new photo', '.cutout'); await until(() => js("library.items.length===2 && !document.querySelector('.cutout[open]')"))
      assert.equal(await js('library.activeItem.width'), 1024); assert.equal(await js('library.activeItem.height'), 1024)
      assert.equal(await js("library.activeItem.extensions['ai-cutout'].studio.frame.mode"), 'product')
      assert.equal(await js('library.activeItem.metadata.Software'), 'Imejii / AI subject composition')
      assert.equal(await js('JSON.stringify({name:library.items[0].name,edits:library.items[0].edits,width:library.items[0].width,height:library.items[0].height})'), original)
      await js("stores()._s.get('drafts').exportCurrent()")
      const bytes = await fs.readFile(saved.at(-1)), length = bytes.readUInt32BE(8), header = JSON.parse(bytes.subarray(12, 12 + length))
      assert.equal(header.state.extensions['ai-cutout'].geometry.width, 1024)
      if (report) await fs.writeFile(path.join(report, 'studio-result.png'), bytes.subarray(12 + length))
    })
    await check('Subject mask hands off to LaMa, protects core actions and remains clearable/restorable', async () => {
      await js('library.select(library.items[0].id)'); await until(() => js('!library.isDecoding && !library.isRendering'))
      await click('Cut out the subject'); await ready(); await click('Send', '.studio-navigation')
      await click('Open in Object removal', '.studio-controls'); await until(() => js("!!document.querySelector('.removal[open]') || !!document.querySelector('.cutout .error')"))
      assert.equal(await js("document.querySelector('.cutout .error')?.textContent"), undefined)
      assert.equal(await js("document.querySelectorAll('dialog[open]').length"), 1)
      assert.ok(await js("document.querySelector('.transfer-note').textContent.includes('subject')"))
      wc.send('menu:action', 'mode:logo'); wc.send('menu:action','rotate:right'); await pause(100); assert.equal(await js('ui.mode'), 'images')
      await click('Clear', '.removal'); assert.equal(await js("[...document.querySelectorAll('.removal button')].find(b=>b.textContent.trim()==='Remove object').disabled"), true)
      await click('Restore transferred mask', '.removal'); await shot('studio-lama-mask.png')
    })
    await check('Real LaMa processes the transferred subject offline and saves its mask provenance', async () => {
      const start = Date.now(); await click('Remove object', '.removal')
      await until(() => js("[...document.querySelectorAll('.removal button')].some(b=>b.textContent.trim()==='Apply as new photo' && !b.disabled) || !!document.querySelector('.removal .error')"), 150000)
      assert.equal(await js("document.querySelector('.removal .error')?.textContent"), undefined)
      await shot('studio-lama-result.png'); await click('Apply as new photo', '.removal')
      await until(() => js("library.items.length===3 && !document.querySelector('.removal[open]')"))
      assert.equal(await js("library.activeItem.extensions['ai-remove'].mask.initial.model"), 'birefnet-lite-v1')
      assert.equal(await js('library.activeItem.width'), JSON.parse(original).width)
      assert.equal(await js("[...document.querySelectorAll('.local-model-panel button')].find(b=>b.textContent.trim()==='Cut out the subject').disabled"), false)
      return { elapsedMs: Date.now() - start }
    })
  } catch (error) { console.error(error) }
  console.log(JSON.stringify({ results, errors, scratch }, null, 2))
  if (report) await fs.writeFile(path.join(report, process.env.IMEJII_PACKAGED_MAIN ? 'studio-asar.json' : 'studio-desktop.json'), JSON.stringify({ results, errors }, null, 2))
  clearTimeout(deadline); window.destroy(); app.exit(results.length < 8 || results.some(r=>r.status==='FAIL') || errors.length ? 1 : 0)
}).catch(error => { console.error(error, errors); clearTimeout(deadline); app.exit(2) })
