<script setup>
import { ref } from 'vue'
import SliderControl from '../../components/ui/SliderControl.vue'
import AppButton from '../../components/ui/AppButton.vue'
import { studioSettings, studioPreset, RATIOS } from './studio.js'
const props = defineProps({ settings: { type: Object, required: true }, section: String, disabled: Boolean, backgroundName: String })
const emit = defineEmits(['update:settings', 'background-image', 'handoff', 'export-mask', 'export-bundle', 'open-studio'])
const selectedRegion = ref('subject'), transferRegion = ref('subject')
function preset(name) { emit('update:settings', studioPreset(name), true) }
function change(group, key, value) {
  const next = studioSettings(props.settings); next[group][key] = value
  if (group === 'background' && key === 'kind' && value === 'original') {
    if (next.frame.mode === 'product') next.frame.mode = 'original'
    next.placement = { scale: 100, x: 0, y: 0, opacity: 100 }; next.sticker.width = next.sticker.opacity = 0
  }
  if (group === 'frame' && key === 'mode' && value === 'product' && next.background.kind === 'original') next.background.kind = 'color'
  if (group === 'frame' && key === 'mode' && value === 'crop') next.placement = { scale: 100, x: 0, y: 0 }
  emit('update:settings', studioSettings(next))
}
function selectRegion(value) {
  selectedRegion.value = value
  if (value === 'surroundings' && props.settings.background.kind === 'transparent') change('background', 'kind', 'original')
}
const adjustmentControls = [
  ['exposure', 'exposure', -2, 2, .05, 'EV'], ['temperature', 'warmth', -100, 100, 1, ''],
  ['tint', 'tint', -100, 100, 1, ''], ['contrast', 'contrast', -100, 100, 1, ''],
  ['saturation', 'saturation', -100, 100, 1, ''], ['sharpen', 'sharpness', 0, 100, 1, '%'],
]
</script>
<template>
  <fieldset class="studio-controls" :disabled="disabled">
    <template v-if="section === 'develop'">
      <div class="studio-heading"><span>ONE MASK, TWO LOOKS</span><h3>Develop independently</h3></div>
      <div class="studio-presets" aria-label="Subject looks">
        <button v-for="[id, label] in [['photo', 'Natural photo'], ['portrait', 'Portrait blur'], ['splash', 'Color splash']]" :key="id" type="button" @click="preset(id)">{{ label }}</button>
      </div>
      <div class="studio-switch" role="group" aria-label="Adjustment region">
        <button type="button" :aria-pressed="selectedRegion === 'subject'" @click="selectRegion('subject')">Subject</button>
        <button type="button" :aria-pressed="selectedRegion === 'surroundings'" @click="selectRegion('surroundings')">Background</button>
      </div>
      <label class="studio-field">{{ selectedRegion === 'subject' ? 'Subject' : 'Background' }} look
        <select :value="settings[selectedRegion].look" @change="change(selectedRegion, 'look', $event.target.value)"><option value="natural">Natural</option><option value="bw">Black &amp; white</option><option value="warm">Warm</option><option value="cool">Cool</option></select>
      </label>
      <SliderControl v-for="[key, label, min, max, step, unit] in adjustmentControls" :key="key" :model-value="settings[selectedRegion][key]" :label="(selectedRegion === 'subject' ? 'Subject ' : 'Background ') + label" :min="min" :max="max" :step="step" :unit="unit" :disabled="disabled" @update:model-value="change(selectedRegion, key, $event)" />
      <p>Soft mask transitions blend the two treatments. Your source colors are never generated by AI.</p>
    </template>
    <template v-else-if="section === 'background'">
      <div class="studio-heading"><span>SET THE SCENE</span><h3>Background</h3></div>
      <label class="studio-field">Background type<select :value="settings.background.kind" @change="change('background', 'kind', $event.target.value)">
        <option value="transparent">Transparent</option><option value="original">Original photo</option><option value="color">Solid color</option><option value="gradient">Gradient</option><option value="image">Your image</option>
      </select></label>
      <template v-if="['color', 'gradient', 'image'].includes(settings.background.kind)">
        <label class="studio-color">{{ settings.background.kind === 'image' ? 'Canvas color' : 'Background color' }}<input type="color" :value="settings.background.color" @input="change('background', 'color', $event.target.value)"></label>
      </template>
      <template v-if="settings.background.kind === 'gradient'">
        <label class="studio-color">Second gradient color<input type="color" :value="settings.background.color2" @input="change('background', 'color2', $event.target.value)"></label>
        <SliderControl :model-value="settings.background.angle" label="Gradient angle" :min="0" :max="360" unit="°" :disabled="disabled" @update:model-value="change('background', 'angle', $event)" />
      </template>
      <template v-if="settings.background.kind === 'image'">
        <AppButton icon="image" @click="emit('background-image')">Choose background image</AppButton><p class="studio-filename">{{ backgroundName || 'Choose a local photo. No upload.' }}</p>
        <label class="studio-field">Image fit<select :value="settings.background.fit" @change="change('background', 'fit', $event.target.value)"><option value="cover">Cover canvas</option><option value="contain">Fit entire image</option></select></label>
        <SliderControl v-for="axis in ['x', 'y']" :key="axis" :model-value="settings.background[axis]" :label="'Background position ' + axis.toUpperCase()" :min="0" :max="100" unit="%" :disabled="disabled" @update:model-value="change('background', axis, $event)" />
      </template>
      <SliderControl v-if="settings.background.kind !== 'transparent'" :model-value="settings.background.blur" label="Background blur" :min="0" :max="30" :step=".5" unit="px" :disabled="disabled" @update:model-value="change('background', 'blur', $event)" />
      <p v-if="settings.background.kind === 'original'">Uniform background blur, not depth-aware lens simulation. Foreground colors are excluded from the blur samples.</p>
      <p v-else>Unlike the preview checkerboard, this background is part of your saved photo. Use Develop → Background to adjust its look.</p>
    </template>
    <template v-else-if="section === 'frame'">
      <div class="studio-heading"><span>GIVE IT SPACE</span><h3>Frame &amp; finish</h3></div>
      <div class="studio-presets"><button type="button" @click="preset('product')">Product photo</button><button type="button" @click="preset('sticker')">Sticker</button></div>
      <label class="studio-field">Framing<select :value="settings.frame.mode" @change="change('frame', 'mode', $event.target.value)"><option value="original">Original dimensions</option><option value="crop">Subject-aware crop</option><option value="product">Centered product / sticker</option></select></label>
      <template v-if="settings.frame.mode !== 'original'">
        <label class="studio-field">Aspect ratio<select :value="settings.frame.ratio" @change="change('frame', 'ratio', $event.target.value)"><option v-for="ratio in RATIOS" :key="ratio" :value="ratio">{{ ratio === 'free' ? (settings.frame.mode === 'crop' ? 'Subject bounds' : 'Original ratio') : ratio }}</option></select></label>
        <SliderControl :model-value="settings.frame.padding" label="Subject margin" :min="0" :max="35" unit="%" :disabled="disabled" @update:model-value="change('frame', 'padding', $event)" />
      </template>
      <label v-if="settings.frame.mode === 'product'" class="studio-field">Output longest edge<select :value="settings.frame.size" @change="change('frame', 'size', Number($event.target.value))"><option v-for="size in [1024, 2048, 4096]" :key="size" :value="size">{{ size }} px</option></select></label>
      <p v-if="settings.frame.mode === 'crop'">The crop follows the visible subject and your corrected mask. This is a proposal: review it before applying. Multiple subjects stay one selection.</p>
      <template v-if="settings.background.kind !== 'original'">
        <SliderControl :model-value="settings.placement.opacity" label="Subject opacity" :min="0" :max="100" unit="%" :reset-value="100" :disabled="disabled" @update:model-value="change('placement', 'opacity', $event)" />
        <template v-if="settings.frame.mode !== 'crop'">
          <SliderControl :model-value="settings.placement.scale" label="Subject scale" :min="20" :max="200" unit="%" :reset-value="100" :disabled="disabled" @update:model-value="change('placement', 'scale', $event)" />
          <SliderControl v-for="axis in ['x', 'y']" :key="axis" :model-value="settings.placement[axis]" :label="'Subject position ' + axis.toUpperCase()" :min="-50" :max="50" unit="%" :disabled="disabled" @update:model-value="change('placement', axis, $event)" />
        </template>
        <SliderControl :model-value="settings.sticker.width" label="Outline width" :min="0" :max="20" :step=".5" unit="px" :disabled="disabled" @update:model-value="change('sticker', 'width', $event)" />
        <label v-if="settings.sticker.width" class="studio-color">Outline color<input type="color" :value="settings.sticker.color" @input="change('sticker', 'color', $event.target.value)"></label>
        <SliderControl :model-value="settings.sticker.opacity" label="Shadow opacity" :min="0" :max="80" unit="%" :disabled="disabled" @update:model-value="change('sticker', 'opacity', $event)" />
        <template v-if="settings.sticker.opacity">
          <SliderControl :model-value="settings.sticker.softness" label="Shadow softness" :min="0" :max="40" unit="px" :disabled="disabled" @update:model-value="change('sticker', 'softness', $event)" />
          <SliderControl v-for="axis in ['x', 'y']" :key="axis" :model-value="settings.sticker[axis]" :label="'Shadow offset ' + axis.toUpperCase()" :min="-40" :max="40" unit="px" :disabled="disabled" @update:model-value="change('sticker', axis, $event)" />
        </template>
        <p>Leave room for the outline and shadow. Position or scale changes can move parts of the subject outside the canvas. Effect pixels are relative to a 1024 px edge.</p>
      </template>
      <p v-else>For a movable subject, outlines or shadows, choose a transparent or replacement background first.</p>
    </template>
    <template v-else-if="section === 'send'">
      <div class="studio-heading"><span>REUSE YOUR SELECTION</span><h3>Send the mask</h3></div>
      <label class="studio-field">Selected area<select v-model="transferRegion"><option value="subject">Subject</option><option value="background">Background</option></select></label>
      <AppButton variant="primary" icon="wand" @click="emit('handoff', transferRegion)">Open in Object removal</AppButton>
      <p>Uses the original working photo and your corrected mask, not this composition. LaMa must be downloaded. Nothing is removed until you review and run it there.</p>
      <AppButton icon="download" @click="emit('export-mask', transferRegion)">Export mask PNG</AppButton>
      <AppButton icon="wand" @click="emit('open-studio', transferRegion)">Open in AI Studio</AppButton>
      <AppButton icon="download" @click="emit('export-bundle', transferRegion)">Export image + mask for SDXL</AppButton>
      <p>White = selected / repaint. Black = preserve. AI Studio receives the working photo before these composition styles, plus your corrected selection. Review the prompt there before running SDXL.</p>
    </template>
  </fieldset>
</template>
<style scoped>
.studio-controls { border: 0; padding: 0; margin: 0; min-width: 0; display: flex; flex-direction: column; gap: 17px; }
.studio-heading span { color: var(--accent-text); font-size: 9px; letter-spacing: .11em; }
h3 { margin: 6px 0 0; font-size: 16px; letter-spacing: -.02em; }
.studio-presets { display: flex; flex-wrap: wrap; gap: 5px; }
.studio-presets button, .studio-switch button { padding: 7px 9px; border: 1px solid var(--border); border-radius: var(--radius-sm); background: var(--bg-input); color: var(--text-muted); font-size: 11px; }
.studio-presets button:hover { color: var(--accent-text); border-color: var(--accent); }
.studio-switch { display: flex; gap: 4px; }
.studio-switch button { flex: 1; }
.studio-switch button[aria-pressed=true] { background: var(--accent-soft); color: var(--accent-text); }
.studio-field { display: flex; flex-direction: column; gap: 7px; font-size: 11px; color: var(--text-muted); }
select { width: 100%; padding: 8px; background: var(--bg-input); color: var(--text); border: 1px solid var(--border); border-radius: var(--radius-sm); font: inherit; }
.studio-color { display: flex; justify-content: space-between; align-items: center; gap: 10px; font-size: 11px; color: var(--text-muted); }
input[type=color] { width: 38px; height: 26px; padding: 1px; border: 1px solid var(--border); background: transparent; }
p { font-size: 11px; line-height: 1.65; color: var(--text-subtle); margin: 0; }
.studio-filename { overflow-wrap: anywhere; }
:disabled { cursor: not-allowed; opacity: .45; }
</style>
